services:
  spark-lakehouse:
    build: .
    image: poia-iot:latest
    container_name: spark_delta_lakehouse
    ports:
      - "8888:8888"
      - "4040:4040"
      - "8501:8501"
    volumes:
      - ./notebooks:/app/notebooks
      - ./lakehouse:/app/lakehouse
    environment:
      - LAKEHOUSE_PATH=/app/lakehouse
      - LOG_FILE_PATH=/app/lakehouse/alertas.log
    user: root
    restart: unless-stopped
    command: bash /app/notebooks/start.sh
