sonar.organization=trickershile
sonar.projectKey=trickershile_Plataforma-de-Observabilidad
sonar.sources=notebooks
sonar.tests=tests
sonar.exclusions=lakehouse/**
sonar.python.coverage.reportPaths=coverage.xml
