---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-observabilidad-logs
  namespace: observabilidad
spec:
  selector:
    matchLabels:
      app: lakehouse-app
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_operation:
              value: "$(request.url_path)"
            source_app:
              value: "$(source.workload.name)"
            destination_app:
              value: "$(destination.workload.name)"
  accessLogging:
    - providers:
        - name: envoy
      filter:
        expression: |
          response.code >= 400
      match:
        mode: SERVER
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-prometheus
  namespace: observabilidad
spec:
  hosts:
    - prometheus.monitoring.svc.cluster.local
  ports:
    - number: 9090
      name: http-metrics
      protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-kiali
  namespace: observabilidad
spec:
  hosts:
    - kiali.istio-system.svc.cluster.local
  ports:
    - number: 20001
      name: http-kiali
      protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL
